- hosts: localhost
  gather_facts: no
  tasks:
  - set_fact:
      my_dict:
        key_1: value_1
        key_2: value_2

  - ansible.utils.update_fact:
      updates:
        - path: my_dict.key_1
          value: changed_value_1
    register: updated

  - set_fact:
      new_dict: "{{ my_dict | combine({'key_1': 'new_value' }) }}"

  - debug: var=my_dict
  - debug: var=updated.my_dict
  - debug: var=new_dict